# Site settings
title: Cloud FE
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Cloud FE's official blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cloud-fe.github.io" # the base hostname & protocol for your site
twitter_username: cloud-fe
github_username:  cloud-fe

# Build settings
markdown: kramdown
